version: "3.7"

services:
  server:
    build: ./server
    ports:
      - 4000:4000

  client:
    build: ./client
    environment:
      SERVER_HOST: localhost

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: