version: "3.7"

services:
  server:
    build: ./server
    ports:
      - 4000:4000
    environment:
      PGUSER: postgres
      PGHOST: database
      PGPASSWORD: postgres

  client:
    build: ./client
    ports:
      - 80:80
    environment:
      SERVER_HOST: keep-lite_default

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
